FROM --platform=$TARGETOS/$TARGETARCH alpine:latest

LABEL org.opencontainers.image.source="https://github.com/Rejected-Pixels/yolks"
LABEL org.opencontainers.image.licenses=MIT

RUN apk add --no-cache ca-certificates curl wget